arxiv_search:
  max_results: 10
  sort_by: "relevance"
  sort_order: "descending"
  paper_dump_path: "./data/papers/"

embedding_db:
  db_save_path: "./data/embedding_db/"
  distance_method: "cosine"
  max_results: 10

llm:
  model_name: "orca-mini-3b-gguf2-q4_0.gguf"
  temparature: 0.1
  max_gen_tokens: 1024
  top_k: 20
  device: "cpu"
  top_p: 0.6
  repeat_penalty: 1.9
  repeat_last_n: 64
  streaming: false
  prompt_template_path: "./data/llm/templates/prompt_template.txt"
  system_template_path: "./data/llm/templates/system_template.txt"